spring.config.activate.on-profile=default
flyway.enabled=true
flyway.user=${POSTGRES_USER}
flyway.password=${POSTGRES_PASSWORD}
flyway.schemas=${POSTGRES_DB}
flyway.url=${POSTGRES_URL}
flyway.locations=filesystem:db/migration

spring.config.activate.on-profile=tests
flyway.enabled=false